### ISSUE TITLE
Ver-ID-UI-Android not working in ANDROID 6 marshamallow 

### ISSUE THREAD

**Issue by AjitSingh199294** [AppliedRecognition/Ver-ID-UI-Android#10]
**Describe the bug**
while installing app in ANDROID 6 [MARSHMALLOW] it gives an error mentioned below

com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Certificate has unsupported critical extension: [2.5.29.37]

**Comment by jakubdolejs** [comment]
Hello @AjitSingh199294,

Is this in the sample app from the Ver-ID UI repository?

Do you mind posting the exception's stack trace and steps how to reproduce the problem?

Regards,
Jakub Dolejs

**Comment by AjitSingh199294** [comment]
Hello @jakubdolejs 

No this is not from the sample app it is coming inside my application which I have already updated on play store and it is working fine in all other devices it is giving crash only in android 6 and also some user facing issues in android R.

Steps to reproduce the problem:
1. Install application in android 6.
2.In application class when I am trying to load the VerId it shows the error failed to load VERID in error activity.

Detailed message is :

java.lang.Exception: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Certificate has unsupported critical extension: [2.5.29.37]

Regards
Ajit Singh

**Comment by AjitSingh199294** [comment]
@jakubdolejs I also checked in sample application and I am facing same issue.

**Comment by jakubdolejs** [comment]
Hello @AjitSingh199294,

Do you mind sharing the following?
1. Device make and model
2. Your application's package name
3. Full stack trace from the exception

Regards,
Jakub

**Comment by AjitSingh199294** [comment]
Hello @jakubdolejs 

I have tested in Samsung galaxy A5.
my application package is "cispl.joshhighsir"

this is full stack trace
cispl.joshhighsir.face_recognition.SampleApplication.veridFactoryDidFailWithException(SampleApplication.java:109)
com.appliedrec.verid.core.VerIDFactory.lambda$null$1$VerIDFactory(VerIDFactory.java:228)
com.appliedrec.verid.core.-$$Lambda$VerIDFactory$E-LUz3LYAvXTurmba9LDobWkAJo.run(lambda)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:148)
android.app.ActivityThread.main(ActivityThread.java:7331)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

![image](https://user-images.githubusercontent.com/77236511/109461881-ce498e00-7a88-11eb-848c-6de602a893f1.png)




> Hello @AjitSingh199294,
> 
> Do you mind sharing the following?
> 
> 1. Device make and model
> 2. Your application's package name
> 3. Full stack trace from the exception
> 
> Regards,
> Jakub

**Comment by jakubdolejs** [comment]
Hello @AjitSingh199294, 
Were you able to collect the device make and model, your app's package name and the stack trace? Is the issue still happening with one of the later releases? Please let me know. Otherwise I'll close the issue.
Thank you,
Jakub

**Comment by jakubdolejs** [comment]
Fixed in 46ac66feec84ef7bdd257bcba9c1547b28ccb4b2 (version 1.21.9)
