### ISSUE TITLE
I want outside the white circle, that is, besides the scan area, it will be black. So how can I set it, hope you can support me.

### ISSUE THREAD

**Issue by PhongAOS** [AppliedRecognition/Ver-ID-UI-Android#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S5]
 - Android version: [e.g. 7.1.1]
 - Ver-ID SDK version [e.g. 1.1.0]

**Additional context**

**Comment by jakubdolejs** [comment]
Hello @PhongAOS, can you post a screen shot so we can better understand your request? Thank you.

**Comment by PhongAOS** [comment]
> Hello @PhongAOS, can you post a screen shot so we can better understand your request? Thank you.

I want outside the circle it is gray or black.
![Screenshot_20190724-180318](https://user-images.githubusercontent.com/52943564/61788992-b8e89880-ae3d-11e9-949b-b924f8c53a57.png)


-

**Comment by jakubdolejs** [comment]
You can overwrite the VerIDSessionFragment and supply your colour in the `getOvalColourFromFaceDetectionStatus` method: https://github.com/AppliedRecognition/Ver-ID-UI-Android/blob/2757536e2f6ce61de2c7b916983a27dd53c948ff/veridui/src/main/java/com/appliedrec/verid/ui/VerIDSessionFragment.java#L602

**Comment by PhongAOS** [comment]
> You can extend the VerIDSessionFragment class and supply your colour in the `getOvalColourFromFaceDetectionStatus` method:
> 
> https://github.com/AppliedRecognition/Ver-ID-UI-Android/blob/2757536e2f6ce61de2c7b916983a27dd53c948ff/veridui/src/main/java/com/appliedrec/verid/ui/VerIDSessionFragment.java#L602

**I mean, outside the scan area, it is more gray in the scan area (Outside the circular area)**

**Comment by jakubdolejs** [comment]
That colour is set here: https://github.com/AppliedRecognition/Ver-ID-UI-Android/blob/2757536e2f6ce61de2c7b916983a27dd53c948ff/veridui/src/main/java/com/appliedrec/verid/ui/VerIDSessionFragment.java#L74
It's a private member so you won't be able to override it but you're welcome to download the source and change it.

**Comment by PhongAOS** [comment]
> That colour is set here:
> 
> https://github.com/AppliedRecognition/Ver-ID-UI-Android/blob/2757536e2f6ce61de2c7b916983a27dd53c948ff/veridui/src/main/java/com/appliedrec/verid/ui/VerIDSessionFragment.java#L74
> 
> 
> It's a private member so you won't be able to override it but you're welcome to download the source and change it.

It only shows for a few seconds at the beginning, it will return to its original state without the scan set.
Here is my code :
- Class: VerIDSessionFragment
private int backgroundColour = 0xFF36AF00;
- Class: FaceGuidePreferenceFragment
detectedFaceView.setFaceRect(faceRect, null, getContext().getResources().getColor(R.color.verid_green), 0xFF36AF00, null, null);

Hope you help me further.

**Comment by PhongAOS** [comment]
I also want to increase the speed of face scanning faster. For example, when the show says "Great, hold it" is on the Success screen. As I did, it will wait about 30 seconds before the screen is successful.

**Comment by jakubdolejs** [comment]
Hi @PhongAOS, can you please contact us at support@appliedrec.com and tell us a bit more about your project? We'll be happy to assist you in integrating Ver-ID into your app.

**Comment by PhongAOS** [comment]
> Hi @PhongAOS, can you please contact us at [support@appliedrec.com](mailto:support@appliedrec.com) and tell us a bit more about your project? We'll be happy to assist you in integrating Ver-ID into your app.


Help me please
- First, I fixed the spherical ring in the middle of the screen, not allowing it to move.
- Secondly, I put the face half inside, half outside the sphere, it still recognized.
- Finally, what I want is that only when the face is put in is it recognized. Can you show me the class or face recognition function?
