### ISSUE TITLE
VerIDSDKIdentity is marked as deprecated

### ISSUE THREAD

**Issue by mariuspena** [AppliedRecognition/Ver-ID-UI-Android#4]
What should I use instead ?

**Comment by jakubdolejs** [comment]
@mariuspena, the class has been renamed to [VerIDIdentity](https://appliedrecognition.github.io/Ver-ID-SDK-Identity-Android/) for consistency with other platforms.

**Comment by mariuspena** [comment]
@jakubdolejs
